{% set name = "nbwipers" %}
{% set version = "0.6.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15d990c3085b9d5291ff1473d893605d032b3060330d28bfc7634af0e6c8bc65

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - nbwipers --help

about:
  home: https://github.com/felixgwilliams/nbwipers
  summary: nbwipers is a command line tool to wipe clean jupyter notebooks, written in Rust.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - felixgwilliams
