{% set name = "nbwipers" %}
{% set version = "0.6.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d27ffd2c5e0ad6f52698aaa33194f16223394c21853ec9c250f00f56b554f0a9

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - nbwipers --help

about:
  home: https://github.com/felixgwilliams/nbwipers
  summary: nbwipers is a command line tool to wipe clean jupyter notebooks, written in Rust.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - felixgwilliams
